#Splunk Connect for Kubernets Values.yaml configuration for SDDS_events and SDDS_metrics
global:
  logLevel: info
  splunk:
    hec:
      host: <HEC HOST>
      port: <HEC PORT>
      token: <HEC TOKEN>
      protocol: https
      insecureSSL: true
  kubernetes:
    clusterName: "sddsPod"
    openshift: true
splunk-kubernetes-logging:
  enabled: true
  logLevel: info
  splunk:
    hec:
      indexName: sdds_events
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  journalLogPath: /var/log/journal

splunk-kubernetes-metrics:
  kubernetes:
    insecureSSL: true 

  # RBAC is disabled
  rbac:
    create: false

  # do not create service account
  serviceAccount:
    create: false

  splunk:
    hec:
      token: <HEC TOKEN>
      host: <HEC HOST>
      port: <HEC PORT>
      protocol: https
      indexName: sdds_metrics
      # connection to splunk is insecure
      insecureSSL: true
